import { Team } from '../model/Team';

export const TEAMS: Team[] = [
{'ID': 48, 'City': 'Buffalo', 'Name': 'Bills',
    'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/BUF.svg'},
{'ID': 49, 'City': 'Miami', 'Name': 'Dolphins',
    'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/MIA.svg'},
{'ID': 50, 'City': 'New England', 'Name': 'Patriots',
    'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/NE.svg'},
{'ID': 51, 'City': 'New York', 'Name': 'Jets',
    'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/NYJ.svg'},
{'ID': 52, 'City': 'Dallas', 'Name': 'Cowboys',
    'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/DAL.svg'},
{'ID': 53, 'City': 'New York', 'Name': 'Giants', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/NYG.svg'},
{'ID': 54, 'City': 'Philadelphia', 'Name': 'Eagles', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/PHI.svg'},
{'ID': 55, 'City': 'Washington', 'Name': 'Redskins', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/WAS.svg'},
{'ID': 56, 'City': 'Baltimore', 'Name': 'Ravens', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/BAL.svg'},
{'ID': 57, 'City': 'Cincinnati', 'Name': 'Bengals', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/CIN.svg'},
{'ID': 58, 'City': 'Cleveland', 'Name': 'Browns', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/CLE.svg'},
{'ID': 59, 'City': 'Pittsburgh', 'Name': 'Steelers', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/PIT.svg'},
{'ID': 60, 'City': 'Chicago', 'Name': 'Bears', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/CHI.svg'},
{'ID': 61, 'City': 'Detroit', 'Name': 'Lions', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/DET.svg'},
{'ID': 62, 'City': 'Green Bay', 'Name': 'Packers', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/GB.svg'},
{'ID': 63, 'City': 'Minnesota', 'Name': 'Vikings', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/MIN.svg'},
{'ID': 64, 'City': 'Houston', 'Name': 'Texans', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/IND.svg'},
{'ID': 65, 'City': 'Indianapolis', 'Name': 'Colts', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/IND.svg'},
{'ID': 66, 'City': 'Jacksonville', 'Name': 'Jaguars', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/JAX.svg'},
{'ID': 67, 'City': 'Tennessee', 'Name': 'Titans', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/TEN.svg'},
{'ID': 68, 'City': 'Atlanta', 'Name': 'Falcons', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/ATL.svg'},
{'ID': 69, 'City': 'Carolina', 'Name': 'Panthers', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/CAR.svg'},
{'ID': 70, 'City': 'New Orleans', 'Name': 'Saints', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/NO.svg'},
{'ID': 71, 'City': 'Tampa Bay', 'Name': 'Buccaneers', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/TB.svg'},
{'ID': 72, 'City': 'Denver', 'Name': 'Broncos', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/DEN.svg'},
{'ID': 73, 'City': 'Kansas City', 'Name': 'Cheifs', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/KC.svg'},
{'ID': 74, 'City': 'Oakland', 'Name': 'Raiders', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/OAK.svg'},
{'ID': 75, 'City': 'Los Angeles', 'Name': 'Chargers', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/LAC.svg'},
{'ID': 76, 'City': 'Arizona', 'Name': 'Cardinals', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/ARI.svg'},
{'ID': 77, 'City': 'Los Angeles', 'Name': 'Rams', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/LA.svg'},
{'ID': 78, 'City': 'San Francisco', 'Name': '49ers', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/SF.svg'},
{'ID': 79, 'City': 'Seattle', 'Name': 'Seahawks', 'officialImageSrc': 'https://static.nfl.com/static/content/public/static/wildcat/assets/img/logos/teams/SEA.svg'},
];
